id: P009193
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-19 19:27:24.681673
source_metadata:
  id: bdr:W1KG25353
  title: བསྟོད་སྨོན་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    194184d8b25445aa986c593603a05433:
      image_group_id: I1KG25355
      title: ''
      volume_number: 1
      total_pages: 422
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
